- name: Project for Homework Assignment
  command: |
    tower-cli project create --name "{{proj_name}}" --description "{{proj_desc}}" --organization "{{org_name}}" --scm-type "{{scm_type}}" --scm-url "{{scm_url}}" --scm-branch "{{scm_branch}}"  --scm-update-on-launch "{{scm_update_on_launch}}"
