---

# vars file for roles/config-tower

proj_name: "00_Homework Assignment"
proj_desc: "Project for Homework Assignment Lab"
org_name: Default 
scm_type: "git"
scm_url: "{{ lookup('env','GITHUB_REPO') }}"
scm_branch: "{{ lookup('env','GIT_BRANCH') }}"

vault_name: yum_repo_vault

group_name: workstation
host_name: workstation-{{ lookup('env','OSP_GUID') }}.{{ lookup('env','OSP_DOMAIN') }}
user_name: admin 
password: r3dh4t1!


# common vars 
static_inventory_name: scm_inventory
ssh_cred_name: "Connect_to_workstation"

# OSP common vars 
instance_group_name: osp
user_cred_name: "cloud-user"
user_cred_path: "/root/.ssh/openstack.pem"

# AWS common vars 
ec2_dynamic_inventory: "Prod Three tier inventory"
opentlc_cred_name: "Opentlc key"


# JTs for RHOSP QA Env
job_template_name_osp_instances: "02_Provision QA Env"
osp_instances_playbook: site-osp-instances.yml

job_template_name_3tier_app: "04_3tier app deployment on QA Env"

# ñ also suitable for AWS deploy
app_deploy_playbook: site-3tier-app.yml

job_template_smoke_osp: "05_Smoke test QA Env"
osp_smoke_playbook: site-smoke-osp.yml

job_template_name_osp_instances_delete: "Nuke QA Env"
osp_instances_delete_playbook: site-osp-delete.yml


# JTs for AWS Prod Env
job_template_aws_provision: "01_Provision Prod Env"
aws_provision_playbook: aws_provision.yml

job_template_aws_status_check: "07_Prod Check the status of AWS instances"
aws_status_playbook: aws_status_check.yml

job_template_aws_ssh_keys: "08_Prod SSH keys three tier app"
aws_ssh_playbook: aws_creds.yml

job_template_name_3tier_app_aws: "09_3 tier app on Prod"
# - alread defined for OSP:   app_deploy_playbook: site-3tier-app.yml

job_template_smoke_aws: "10_Smoke test Prod env"
aws_smoke_app_playbook: site-smoketest-aws.yml

# ##################################################################

workflow_template_name: cicd_workflow

ec2_inventory_source: "03_06_Prod Three tier inventory source"
aws_region_name: "{{ lookup('env','REGION') }}"
aws_read_keys: "AWS Access Key"
aws_cred_name: "Creds for AWS instances"

tag_filters: "tag:instance_filter=three-tier-app-{{ lookup('env','MAIL_ID') }}"
scm_inventory_source: "SCM three tier inventory source"
path_to_scm_inventory: scm_inventory
